<a href="https://colab.research.google.com/github/PatrickRuan/100-Days-Of-ML-Code/blob/master/Day_038_HW%E7%9A%84%E5%89%AF%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## [作業重點]
使用 Sklearn 中的線性迴歸模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義

## 作業
試著使用 sklearn datasets 的其他資料集 (wine, boston, ...)，來訓練自己的線性迴歸模型。

### HINT: 注意 label 的型態，確定資料集的目標是分類還是回歸，在使用正確的模型訓練！

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets



wine = datasets.load_wine()
boston = datasets.load_boston()
breast_cancer = datasets.load_breast_cancer()

In [0]:
wine.target # <== array([0, 0, 0, 0, 0, 0, 1, 2...   so, it is a classification problem
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

#LCM = sklearn.linear_model.Linear
LCM= linear_model.LogisticRegression()
X_train, X_test, y_train, y_test = train_test_split(wine.data, wine.target,test_size=0.2, random_state=43)
LCM.fit(X_train, y_train)
y_pred = LCM.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f'accuracy is, {acc}')

accuracy is, 1.0


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [0]:
y_pred

array([2, 1, 0, 0, 1, 1, 2, 0, 1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 2, 0, 0,
       0, 0, 2, 0, 2, 1, 0, 1, 0, 1, 2, 1, 0, 1])

In [0]:
y_test

array([2, 1, 0, 0, 1, 1, 2, 0, 1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 2, 0, 0,
       0, 0, 2, 0, 2, 1, 0, 1, 0, 1, 2, 1, 0, 1])

In [0]:
boston = datasets.load_boston()
print(boston.target[:5])  # regression

[24.  21.6 34.7 33.4 36.2]


In [0]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split, KFold
from sklearn import datasets
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [0]:
X_train, X_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=43)
model = linear_model.LinearRegression()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print(f'mse is { mean_squared_error(y_test, pred) }')
print(f'mae is {mean_absolute_error(y_test, pred)}')

mse is 22.01861344950045
mae is 3.291238342730683


In [0]:
breast_cancer = datasets.load_breast_cancer()
print(breast_cancer.target[:5])

from sklearn.model_selection import KFold, train_test_split
from sklearn import linear_model
from kelearn.metrics import accuracy_score

[0 0 0 0 0]


In [0]:
X_train, X_test, y_train, y_test = train_test_split(breast_cancer.data, breast_cancer.target, test_size=0.25, random_state=43)
model = linear_model.LogisticRegression()
model.fit(X_train, y_train)
pred= model.predict(X_test)
print(f'accuracy is {accuracy_score(y_test, pred)}')

accuracy is 0.986013986013986


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [0]:
#try again
import numpy as np
from sklearn import datasets
from sklearn.model_selection import KFold, train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, accuracy_score

In [0]:
wine = datasets.load_wine()
Boston = datasets.load_boston()
diabetes = datasets.load_diabetes()
breast_cancer = datasets.load_breast_cancer()

In [15]:
print(wine.target[:5])
print(Boston.target[:5])
print(diabetes.target[:5])
print(breast_cancer.target[:5])

[0 0 0 0 0]
[24.  21.6 34.7 33.4 36.2]
[151.  75. 141. 206. 135.]
[0 0 0 0 0]


In [0]:
wmodel = LogisticRegression()
Bmodel = LinearRegression()
dmodel = LinearRegression()
bmodel = LogisticRegression()

X_wtrain, X_wtest, y_wtrain, y_wtest = train_test_split(wine.data, wine.target, test_size=0.2, random_state=43)
X_Btrain, X_Btest, y_Btrain, y_Btest = train_test_split(Boston.data, Boston.target, test_size=0.2, random_state=43)
X_dtrain, X_dtest, y_dtrain, y_dtest = train_test_split(diabetes.data, diabetes.target, test_size=0.2, random_state=43)
X_btrain, X_btest, y_btrain, y_btest = train_test_split(breast_cancer.data, breast_cancer.target, test_size=0.2, random_state=43)

In [18]:
wmodel.fit(X_wtrain, y_wtrain)
Bmodel.fit(X_Btrain, y_Btrain)
dmodel.fit(X_dtrain, y_dtrain)
bmodel.fit(X_btrain, y_btrain)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
wpred = wmodel.predict(X_wtest)
acc_w = accuracy_score(y_wtest, wpred)
print(f'accuracy of wine classification is, {acc_w}\n')

Bpred = Bmodel.predict(X_Btest)
mse_B = mean_squared_error(y_Btest, Bpred)
mae_B = mean_absolute_error(y_Btest, Bpred)
print(f'mse of Bonston regression is, {mse_B}, mae is, {mae_B}\n')

dpred = dmodel.predict(X_dtest)
mse_d = mean_squared_error(y_dtest, dpred)
mae_d = mean_absolute_error(y_dtest, dpred)
print(f'mse of diabetes regression is, {mse_d}, mae is, {mae_d}\n')



bpred = bmodel.predict(X_btest)
acc_b = accuracy_score(y_btest, bpred)
print(f'accuracy of breast cancer classification is, {acc_b}')

accuracy of wine classification is, 1.0

mse of Bonston regression is, 22.01861344950045, mae is, 3.291238342730683

mse of diabetes regression is, 2858.2551533228366, mae is, 44.58196796591311

accuracy of breast cancer classification is, 0.9824561403508771
